import type { NextPage } from 'next'
import Head from 'next/head'
import { Canvas, PaintCoords } from '../../components/Canvas'
import styles from './../../styles/Game.module.scss'
import { io, Socket } from 'socket.io-client'
import React from 'react'

const Home: NextPage = () => {
  const socketRef = React.useRef<Socket>()
  React.useEffect(() => {
    socketRef.current = io('http://localhost:3000')

    socketRef.current.on('paint', (data) => {
      console.log(data)
    })
  }, [])

  const onPaint = (data: PaintCoords) => {
    if (socketRef.current) {
      socketRef.current.emit('paint', data)
    }
  }
  return (
    <div>
      <Head>
        <title>Игра</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.game}>
        <div className={styles.chat}>
          <div className={styles.chatTitle}>Чат</div>

          <div className={styles.chatMessages}>
            <div className={styles.chatItem}>
              <b>Name Surname</b>
              <p>Sample text</p>
            </div>
          </div>

          <div className={styles.chatInput}>
            <input type='text' />
            <button>Send</button>
          </div>
        </div>

        <div className={styles.canvas}>
          <Canvas onPaint={onPaint} />
          <div id='paint' />
        </div>
      </div>
    </div>
  )
}

export default Home
