import type { NextPage } from 'next'
import Head from 'next/head'
import { Canvas } from '../../components/Canvas'
import styles from './../../styles/Game.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Игра</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.game}>
        <div className={styles.chat}>
          <div className={styles.chatTitle}>Чат</div>

          <div className={styles.chatMessages}>
            <div className={styles.chatItem}>
              <b>Name Surname</b>
              <p>Sample text</p>
            </div>
          </div>

          <div className={styles.chatInput}>
            <input type='text' />
            <button>Send</button>
          </div>
        </div>

        <div className={styles.canvas}>
          <Canvas />
          <div id='paint' />
        </div>
      </div>
    </div>
  )
}

export default Home
